### ISSUE TITLE
Consider long path awareness

### ISSUE THREAD

**Issue by thewavelength** [nikeee/HolzShots#113]
As HolzShots will have an application manfest file it can indicate long path awareness. If it already is, we just need to uncomment the required line in [app.manifest](https://github.com/thewavelength/HolzShots/commit/821197fedb2bbc3961787a34b447b2f62eb4d265#diff-1ad1e7aa0aec30e73250ff40b6314c6597d0100f94b569fbefdc2b9fab27e652R30).

**Comment by nikeee** [comment]
How do we know if it is?

According to this:
https://stackoverflow.com/a/53920139

Everything should be fine if we're using standard I/O APIs. However, there might be cases where we check the file length manually. I'll check chat.

**Comment by thewavelength** [comment]
No clue about usermode applications. If you say HS is only using compliant APIs, I think this can be enabled without much testing.
