### ISSUE TITLE
background transparency at area selector 

### ISSUE THREAD

**Issue by Daisenki** [nikeee/HolzShots#31]
Can you please made a setting for the background transparency when you make a screenshot with the area selector? I would love to deactivate the feature or made it more transparency or more brighter, because I can't see anything anymore on my display when it is active, it's hard to make the screenshot without seen anything...

The snipping tool from MS doesn't have that.

And I didn't see any different between style 1, style 2 and style 3? What did the change?

**Comment by nikeee** [comment]
I'll add a setting for that.

The styles set the decoration of the rectangle you are drawing. I think I'll drop two of the 3 settings soon.
