### ISSUE TITLE
Replace WindowsAPICodePack with new WinForms APIs

### ISSUE THREAD

**Issue by nikeee** [nikeee/HolzShots#34]
See comments in #15.
TODO:
- [ ] Jumplists (is this possible?)
- [x] FolderBrowserDialog, Browser dialogs: dotnet/winforms#57
- [x] TaskDialog dotnet/winforms#146

Also, see: dotnet/winforms#181

**Comment by nikeee** [comment]
Jumplists seem to be tricky. They have a long trail of dependencies.

**Comment by RussKie** [comment]
In [Git Extensions .NET 5.0 port](https://github.com/gitextensions/gitextensions/pull/8522) we still use https://github.com/contre/Windows-API-Code-Pack-1.1.

It is totally feasible add JumpList API to Windows Forms codebase, but it will require a detailed API proposal, and a champion like [@kpreisser with Task Dialog API proposal](https://github.com/dotnet/winforms/issues/146).
